### ISSUE TITLE
NPE during Periodic Payment PSU Authentication

### ISSUE THREAD

**Issue by djole87** [adorsys/XS2A-Sandbox#13]
Hi all,

I'm getting Internal Server Error with the NPE exception in the periodic-payments process during execution of the following call 

> PUT /v1/{payment-service}/{payment-product}/{paymentId}/authorisations/{authorisationId}
> Update PSU data for payment initiation with PSU Authentication

Please find attached stack trace
[periodic_payment_auth_exception.txt](https://github.com/adorsys/XS2A-Sandbox/files/4257212/periodic_payment_auth_exception.txt)

Best Regards,
Đorđe

**Comment by jfractalus** [comment]
Hi!
Please, make sure that you used the latest version of Dynamic Sandbox v.3.0 and versions of the following components:

1. Ledgers v.2.9
2. XS2A v.5.10
3. ASPSP-Profile v.5.10
4. Consent-Management v.5.10
5. XS2A Connector-Examples v.5.10

**Comment by djole87** [comment]
Ah...
Will do it and let you know.

Thank you for the fast response.

**Comment by djole87** [comment]
I've removed all containers, images, and volumes.
Ran command  `docker-compose -f docker-compose-release.yml --no-build`.

After Sandbox was successfully run, the same flow for user marion.mueller
  - Payment Initiation Request for Periodic Payment (successfully executed)
  - Update PSU Data with PSU Authentication (fails)

it fails with the same exception.

**Comment by jfractalus** [comment]
Hi. 
1) Why are you using --no-build? We don't have any build section in docker-compose-release.yml. You should use docker-compose -f docker-compose-release.yml up.
2) Please give as request body that you used for payment initiation

**Comment by djole87** [comment]
1. no real reason
2.  ```
{
  "creditorAccount": {
    "currency": "EUR",
    "iban": "DE69760700240340283600"
  },
  "creditorAgent": "BCENEVOD",
  "creditorName": "Vodafone",
  "dayOfExecution": "14",
  "debtorAccount": {
    "currency": "EUR",
    "iban": "DE38760700240320465700"
  },
  "endDate": "2021-10-14",
  "endToEndIdentification": "VOD-123456789",
  "executionRule": "following",
  "frequency": "MONTHLY",
  "instructedAmount": {
    "amount": "44.99",
    "currency": "EUR"
  },
  "remittanceInformationUnstructured": "Ref. Number Vodafone-1222",
  "startDate": "2021-02-14"
}
```

**Comment by jfractalus** [comment]
Here is correct json body for payment initiation for 'marion.muller' user:
{
  "creditorAccount": {
    "currency": "EUR",
    "iban": "DE15500105172295759744"
  },
  "creditorAddress": {
    "streetName": "Breite Gasse",
    "buildingNumber": "34",
    "townName": "Nürnberg",
    "postCode": "90457",
    "country": "DE"
  },
  "creditorAgent": "BCENEVOD",
  "creditorName": "Vodafone",
  "dayOfExecution": "14",
  "debtorAccount": {
    "currency": "EUR",
    "iban": "DE69760700240340283600"
  },
  "endDate": "2020-10-14",
  "endToEndIdentification": "VOD-123456789",
  "executionRule": "following",
  "frequency": "Monthly",
  "instructedAmount": {
    "amount": 44.99,
    "currency": "EUR"
  },
  "remittanceInformationUnstructured": "Ref. Number Vodafone-1222",
  "startDate": "2020-03-05"
}

**Comment by djole87** [comment]
I've used the body from above, and here is response I've got.
```
{
    "tppMessages": [
        {
            "category": "ERROR",
            "code": "PARAMETER_NOT_SUPPORTED",
            "text": "Wrong payment type: periodic-payments"
        }
    ]
}
```

**Comment by jfractalus** [comment]
Did you put proper payment type to the path variable?

**Comment by djole87** [comment]
Yap,

{{protocol}}://{{url_xs2a}}/v1/periodic-payments/{{payment_product}}

**Comment by djole87** [comment]
Here is what I can see in the logs

xs2a-connector-examples       | 2020-03-02 14:46:10.187  INFO 1 --- [nio-8089-exec-7] request-log                              : InR-ID: [aa365791-0c12-488b-a397-cc967e9e6bab], X-Request-ID: [2f77a125-aa7a-45c0-b414-cea25a116035] uri: [/v1/periodic-payments/sepa-credit-transfers], requestHeaders: [accept: application/json, content-type: application/json, psu-id: marion.mueller, psu-ip-address: 1.1.1.1, tpp-explicit-authorisation-preferred: true, x-request-id: 2f77a125-aa7a-45c0-b414-cea25a116035, user-agent: PostmanRuntime/7.22.0, cache-control: no-cache, postman-token: d3f73afd-0cd3-439e-ab6c-458c442f3cff, host: localhost:8089, accept-encoding: gzip, deflate, br, content-length: 648, connection: keep-alive], requestPayload: [{
xs2a-connector-examples       | "creditorAccount": {
xs2a-connector-examples       | "currency": "EUR",
xs2a-connector-examples       | "iban": "DE15500105172295759744"
xs2a-connector-examples       | },
xs2a-connector-examples       | "creditorAddress": {
xs2a-connector-examples       | "streetName": "Breite Gasse",
xs2a-connector-examples       | "buildingNumber": "34",
xs2a-connector-examples       | "townName": "Nürnberg",
xs2a-connector-examples       | "postCode": "90457",
xs2a-connector-examples       | "country": "DE"
xs2a-connector-examples       | },
xs2a-connector-examples       | "creditorAgent": "BCENEVOD",
xs2a-connector-examples       | "creditorName": "Vodafone",
xs2a-connector-examples       | "dayOfExecution": "14",
xs2a-connector-examples       | "debtorAccount": {
xs2a-connector-examples       | "currency": "EUR",
xs2a-connector-examples       | "iban": "DE69760700240340283600"
xs2a-connector-examples       | },
xs2a-connector-examples       | "endDate": "2020-10-14",
xs2a-connector-examples       | "endToEndIdentification": "VOD-123456789",
xs2a-connector-examples       | "executionRule": "following",
xs2a-connector-examples       | "frequency": "Monthly",
xs2a-connector-examples       | "instructedAmount": {
xs2a-connector-examples       | "amount": 44.99,
xs2a-connector-examples       | "currency": "EUR"
xs2a-connector-examples       | },
xs2a-connector-examples       | "remittanceInformationUnstructured": "Ref. Number Vodafone-1222",
xs2a-connector-examples       | "startDate": "2020-03-05"
xs2a-connector-examples       | }], responseStatus: [400], responseHeaders: [], responseBody: [{"tppMessages":[{"category":"ERROR","code":"PARAMETER_NOT_SUPPORTED","text":"Wrong payment type: periodic-payments"}]}] 
xs2a-connector-examples       | 2020-03-02 14:46:10.190  INFO 1 --- [nio-8089-exec-7] access-log                               : InR-ID: [aa365791-0c12-488b-a397-cc967e9e6bab], X-Request-ID: [2f77a125-aa7a-45c0-b414-cea25a116035] RESPONSE - TPP ID: [PSDDE-FAKENCA-87B2AC], Status: [400]

**Comment by jfractalus** [comment]
Show me what you have here:
![image](https://user-images.githubusercontent.com/19815243/75682194-ac62d300-5c9d-11ea-843d-f26a2a802867.png)

**Comment by djole87** [comment]
SINGLE:
        - sepa-credit-transfers
        - instant-sepa-credit-transfers
        - target-2-payments
        - cross-border-credit-transfers
      PERIODIC:
        - sepa-credit-transfers
        - instant-sepa-credit-transfers
        - target-2-payments
        - cross-border-credit-transfers
      BULK:
        - sepa-credit-transfers
        - instant-sepa-credit-transfers
        - target-2-payments
        - cross-border-credit-transfers

**Comment by jfractalus** [comment]
Please use bank_profile from here:
https://github.com/adorsys/XS2A-Sandbox/tree/master/bank-profile

**Comment by djole87** [comment]
Just compared the file you've suggested and the one I'm using and contents of the both files are the same.

**Comment by jfractalus** [comment]
Execute, please curl -X GET "http://127.0.0.1:48080/api/v1/aspsp-profile" -H "accept: */*" and show me the result. What do you have in supportedPaymentTypeAndProductMatrix section? :
![image](https://user-images.githubusercontent.com/19815243/75767164-01105780-5d4b-11ea-96d3-ba2ca9358fec.png)

**Comment by djole87** [comment]
Do you need the whole response?
```
"pis": {
    "supportedPaymentTypeAndProductMatrix": {
      "payments": [
        "sepa-credit-transfers",
        "instant-sepa-credit-transfers"
      ]
    }
```

**Comment by jfractalus** [comment]
That is a problem. 
![image](https://user-images.githubusercontent.com/19815243/75775901-987da680-5d5b-11ea-98d5-f896eaa0b47b.png)

**Comment by jfractalus** [comment]
![image](https://user-images.githubusercontent.com/19815243/75776053-e1355f80-5d5b-11ea-8bd7-d252472f5ccc.png)

**Comment by jfractalus** [comment]
You can take a look inside the docker container and check if bank_prifile_ledgers presented there

**Comment by djole87** [comment]
I've checked xs2a-aspsp-profile container and file bank_profile_ledgers.yml is present in the /opt/profile folder and it's content is listed below:

```
---
setting:
  ais:
    consentTypes:
      bankOfferedConsentSupported: TRUE
      globalConsentSupported: TRUE
      availableAccountsConsentSupported: TRUE
      accountAccessFrequencyPerDay: 4
      notConfirmedConsentExpirationTimeMs: 86400000
      maxConsentValidityDays: 90
      accountOwnerInformationSupported: false
    redirectLinkToOnlineBanking:
      aisRedirectUrlToAspsp: http://localhost:4400/account-information/login?encryptedConsentId={encrypted-consent-id}&redirectId={redirect-id}
    transactionParameters:
      availableBookingStatuses:
        - BOOKED
      transactionsWithoutBalancesSupported: TRUE
      supportedTransactionApplicationTypes:
        - application/json
    deltaReportSettings:
      entryReferenceFromSupported: FALSE
      deltaListSupported: FALSE
    scaRequirementsForOneTimeConsents:
      scaByOneTimeAvailableAccountsConsentRequired: TRUE
      scaByOneTimeGlobalConsentRequired: TRUE
  pis:
    supportedPaymentTypeAndProductMatrix:
      SINGLE:
        - sepa-credit-transfers
        - instant-sepa-credit-transfers
        - target-2-payments
        - cross-border-credit-transfers
      PERIODIC:
        - sepa-credit-transfers
        - instant-sepa-credit-transfers
        - target-2-payments
        - cross-border-credit-transfers
      BULK:
        - sepa-credit-transfers
        - instant-sepa-credit-transfers
        - target-2-payments
        - cross-border-credit-transfers
    maxTransactionValidityDays: 0
    notConfirmedPaymentExpirationTimeMs: 86400000
    paymentCancellationAuthorisationMandated: FALSE
    redirectLinkToOnlineBanking:
      pisRedirectUrlToAspsp: http://localhost:4400/payment-initiation/login?paymentId={encrypted-payment-id}&redirectId={redirect-id}
      pisPaymentCancellationRedirectUrlToAspsp: http://localhost:4400/payment-cancellation/login?paymentId={encrypted-payment-id}&redirectId={redirect-id}
      paymentCancellationRedirectUrlExpirationTimeMs: 600000
    countryValidationSupported: DE
    supportedTransactionStatusFormats:
      - application/json
  piis:
    piisConsentSupported: TRUE
  common:
    scaApproachesSupported:
      - EMBEDDED
      - REDIRECT
      - DECOUPLED
      - OAUTH
    scaRedirectFlow: REDIRECT
    oauthConfigurationUrl: http://localhost:8090/oauth/authorization-server
    startAuthorisationMode: auto
    tppSignatureRequired: FALSE
    psuInInitialRequestMandated: FALSE
    redirectUrlExpirationTimeMs: 600000
    authorisationExpirationTimeMs: 86400000
    forceXs2aBaseLinksUrl: FALSE
    xs2aBaseLinksUrl: http://myhost.com/
    supportedAccountReferenceFields:
      - IBAN
    multicurrencyAccountLevelSupported: SUBACCOUNT
    aisPisSessionsSupported: FALSE
    signingBasketSupported: FALSE
    checkTppRolesFromCertificateSupported: FALSE
    aspspNotificationsSupported:
      - NONE
    authorisationConfirmationRequestMandated: FALSE
    authorisationConfirmationCheckByXs2a: FALSE
    checkUriComplianceToDomainSupported: FALSE
```
